### PR TITLE
Fix user resource parsing/retrieval using FHIR 

### PR DESCRIPTION
**Pull request by ngourley**
@kolkheang these changes were required in order for our SMART app to work with the sandbox:
```javascript
var resource = userId.split("/")[userId.split("/").length - 2];
var uid = userId.split("/")[userId.split("/").length - 1];
```

And to work when launched in Millennium (IE10 compatibility):
```javascript
var pr = jquery.Deferred();
```

Please let me know if there are any questions. Thanks!

### CODE REVIEW

**Comment by kolkheang** [comment]
@ngourley  - Thanks for the contribution.  Could you explain what the issue was?  Were you accessing your app as a standalone launch?  Also, could you explain the -2 offset?

**Comment by ngourley** [comment]
Hey @kolkheang we discussed this a little over a month ago.

When retrieving the current user, the resource is a full url - so currently, the resource split means that resource is "http:", and uid is "". This change grabs the last two parts of the split string so that its the resource and uid, this change is compatible with both:
resource/uid
https://host/etc/resource/uid

Hope this makes sense.

**Review by kolkheang — APPROVED** [review]
Thanks!

**Comment by kolkheang** [comment]
@shriniketsarkar reviewed this PR and he's fine with the changes.

**Comment by kolkheang** [comment]
Thanks @ngourley for this contribution!

**Pull request merged**
